### ISSUE TITLE
Synchronous call to Mailchimp API can block request

### ISSUE THREAD

**Issue by loevgaard** [Setono/SyliusMailchimpPlugin#11]
On this line https://github.com/Setono/SyliusMailchimpPlugin/blob/master/src/EventListener/CustomerNewsletterListener.php#L71 there is a synchronous call to the Mailchimp API which means that 1) it slows down the total time of the request for the customer, and 2) if Mailchimp's API is down it blocks the request.

It needs to be inserted into an export queue or something

**Comment by bitbager** [comment]
Fixed by #13.
