### ISSUE TITLE
AppBundle used?

### ISSUE THREAD

**Issue by loevgaard** [Setono/SyliusMailchimpPlugin#2]
Is [this file](https://github.com/Setono/SyliusMailchimpPlugin/blob/master/tests/Application/src/AppBundle/AppBundle.php) used anywhere?

If not, can we remove it and also remove the entry in composer.json referring to this.

**Comment by loevgaard** [comment]
I am not sure I understand :) It's not in the Sylius plugin skeleton repository, neither is the entry in the `composer.json`

**Comment by bitbager** [comment]
Must be something we missed while updating to 1.3. I think it could be removed :)
