### ISSUE TITLE
Docs issue

### ISSUE THREAD

**Issue by malvor** [Setono/SyliusMailchimpPlugin#35]
In docs you have an incorrect namespace for OrderRepository.
It should be `App\Doctrine\ORM` instead of 
`Tests\Setono\SyliusMailchimpPlugin\Application\Doctrine\ORM`

**Comment by loevgaard** [comment]
Hi @malvor 

Thanks for noticing! Can you make a PR? :)

**Comment by loevgaard** [comment]
This has been fixed
