### ISSUE TITLE
Remove export from naming

### ISSUE THREAD

**Issue by loevgaard** [Setono/SyliusMailchimpPlugin#4]
A lot of places still contain `export` in the naming, i.e. https://github.com/Setono/SyliusMailchimpPlugin/blob/master/src/Resources/config/grids/mailchimp_export.yml

Can you do a search for these? :)

**Comment by bitbager** [comment]
Ok, I will take care of it

**Comment by loevgaard** [comment]
Not quite. There are names from when it was called `SyliusMailChimpExportPlugin`. See this line: https://github.com/Setono/SyliusMailchimpPlugin/blob/master/src/Resources/config/grids/mailchimp_export.yml#L6: `setono_sylius_mailchimp_export_plugin`
