### ISSUE TITLE
Where is handled the PushCustomer message?

### ISSUE THREAD

**Issue by jacquesbh** [Setono/SyliusMailchimpPlugin#67]
Hi!

Where do you handle the PushCustomer message you submit here?
https://github.com/Setono/SyliusMailchimpPlugin/blob/aaf7da7324a550d8316ebecd33d07dd8e447904a/src/EventListener/Doctrine/Customer/PushCustomerToMailchimp.php#L41-L42

I can't find the handler.

**Comment by loevgaard** [comment]
Hi @jacquesbh 

It was removed, because I deemed it unnecessary. However, I forgot to delete the message apparently :)

**Comment by loevgaard** [comment]
Whoops, and from your code example I can see I shouldn't have. I will revert that!

**Comment by jacquesbh** [comment]
🎉

Yes, this message is required actually :p
